stages:
  - build

build-el7-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp *.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    

  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el7-x86_64 openvas-libraries.spec /mnt/repo/atomic-testing/centos/7/x86_64/ ; else  gitlab-build.sh el7-x86_64 openvas-libraries.spec /mnt/repo/atomic-bleeding/centos/7/x86_64/ ; fi )

 

build-el6-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp openvas-libraries.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/


# We always run the asl job last, this way it has the higher release field
  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el6-x86_64 openvas-libraries.spec /mnt/repo/atomic-testing/centos/6/x86_64/ ; else  gitlab-build.sh el6-x86_64 openvas-libraries.spec /mnt/repo/atomic-bleeding/centos/6/x86_64/ ; fi )



# We always run the asl job last, this way it has the higher release field
build-el6-i386:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp openvas-libraries.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el6-i386 openvas-libraries.spec /mnt/repo/atomic-testing/centos/6/i386/ ; else  gitlab-build.sh el6-i386 openvas-libraries.spec /mnt/repo/atomic-bleeding/centos/6/i386/ ; fi )

build-fc24-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp openvas-libraries.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc24-x86_64 openvas-libraries.spec /mnt/repo/atomic-testing/fedora/24/x86_64/ ; else  gitlab-build.sh fc24-x86_64 openvas-libraries.spec /mnt/repo/atomic-bleeding/fedora/24/x86_64/ ; fi )


build-fc25-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp openvas-libraries.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc25-x86_64 openvas-libraries.spec /mnt/repo/atomic-testing/fedora/25/x86_64 ; else  gitlab-build.sh fc25-x86_64 openvas-libraries.spec /mnt/repo/atomic-bleeding/fedora/25/x86_64 ; fi )
